# Generated by Django 4.2.5 on 2023-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture_url', models.URLField(max_length=500)),
                ('user_score', models.CharField()),
                ('ep_watched', models.CharField()),
                ('ep_total', models.CharField()),
            ],
        ),
    ]
