# Generated by Django 4.2.5 on 2023-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_userpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture_url', models.URLField(max_length=500)),
                ('user_score', models.CharField()),
                ('ch_read', models.CharField()),
                ('ch_total', models.CharField()),
            ],
        ),
    ]
