# Generated by Django 4.2.5 on 2023-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_userpage', '0004_mangastats'),
    ]

    operations = [
        migrations.AddField(
            model_name='animestats',
            name='Completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animestats',
            name='Dropped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animestats',
            name='Episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animestats',
            name='OnHold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animestats',
            name='PlanToWatch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animestats',
            name='Rewatched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animestats',
            name='TotalEntries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animestats',
            name='Watching',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='Chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='Completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='Dropped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='OnHold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='PlanToWatch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='Reading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='Reread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='TotalEntries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mangastats',
            name='Volumes',
            field=models.IntegerField(default=0),
        ),
    ]
