# Generated by Django 4.2.4 on 2023-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_userpage', '0009_usermangascore_useranimescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='user_score',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='user_score',
        ),
        migrations.AlterField(
            model_name='usermangascore',
            name='score',
            field=models.CharField(),
        ),
    ]
